# Copy / Paste / Cut
bindd = SUPER, C, Clipboard Copy, sendshortcut, CTRL, Insert,
bindd = SUPER, V, Clipboard Paste, sendshortcut, SHIFT, Insert,
bindd = SUPER, X, Clipboard Cut, sendshortcut, CTRL, X,